import json
import os
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session
from database import get_db
from models.analysis import Analysis
from models.company import Company
from models.fraud import FraudSignal

router = APIRouter()

@router.get("/api/fraud/{analysis_id}")
def get_fraud_results(analysis_id: int, db: Session = Depends(get_db)):
    analysis = db.query(Analysis).filter(Analysis.id == analysis_id).first()
    if not analysis:
        raise HTTPException(status_code=404, detail="Analysis not found")
        
    company = db.query(Company).filter(Company.id == analysis.company_id).first()
    if not company:
        raise HTTPException(status_code=404, detail="Company not found")
        
    fraud_signals = db.query(FraudSignal).filter(FraudSignal.analysis_id == analysis.id).all()
    
    # Load dynamic fraud payload generated by fraud_service ML logic
    json_path = f"data/fraud_{analysis_id}.json"
    fraud_data = {}
    if os.path.exists(json_path):
        with open(json_path, "r") as f:
            fraud_data = json.load(f)
            
    signals_list = fraud_data.get("signals", [])
    
    # Sub-System 1: GST
    gst_sig = next((s for s in signals_list if s.get("signal_type") == "GST_MISMATCH"), {})
    gst_raw = gst_sig.get("raw_data", {})
    # Using defaults assuming there could be missing keys
    
    # Sub-System 2: Circular Trading
    circ_sig = next((s for s in signals_list if s.get("signal_type") == "CIRCULAR_TRADING"), {})
    
    # Sub-System 3: MCA
    mca_sig = next((s for s in signals_list if s.get("signal_type") == "MCA_DIRECTOR"), {})
    mca_raw = mca_sig.get("raw_data", {})
    
    return {
        "gst_detector": {
            "gstr_2a_amount": 0.0, # We lack the raw absolute numbers, but we have mismatch %
            "gstr_3b_amount": 0.0,
            "mismatch_amount": gst_sig.get("evidence_amount", 0.0),
            "confidence_score": gst_sig.get("confidence_score", 100.0),
            "risk_level": gst_sig.get("risk_level", "GOOD"),
            "finding": gst_sig.get("description", "Clean matching between Vendor declarations and Company claims."),
            "research_source": gst_sig.get("source", "GSTN Document/API Comparison")
        },
        "circular_trading": {
            "detected": circ_sig.get("risk_level") == "HIGH",
            "entities_involved": len(circ_sig.get("graph_data", {}).get("nodes", [])) if circ_sig.get("risk_level") == "HIGH" else 0,
            "total_amount_rotated": circ_sig.get("evidence_amount", 0.0),
            "entities": [],
            "graph_data": circ_sig.get("graph_data", {"nodes": [], "edges": []})
        },
        "mca_xray": {
            "promoter_name": "Primary Promoter",
            "din_number": "Not explicitly supplied",
            "disqualified": mca_raw.get("is_disqualified", False),
            "disqualification_reason": mca_sig.get("description", ""),
            "past_companies": [],
            "risk_level": mca_sig.get("risk_level", "GOOD")
        },
        "overall_verdict": {
            "risk_level": fraud_data.get("fraud_risk_level", "LOW"),
            "signals_count": len([s for s in signals_list if s.get("risk_level") in ["MEDIUM", "HIGH"]]),
            "recommendation": "Multiple patterns detected." if fraud_data.get("fraud_risk_level") == "HIGH" else "All three analytics layers show clean baseline profiles. Safe to proceed."
        }
    }

@router.get("/api/fraud/graph/{analysis_id}", response_class=HTMLResponse)
def get_fraud_graph(analysis_id: int):
    # Dynamic PyVis generation embedding real Graph Data
    json_path = f"data/fraud_{analysis_id}.json"
    graph_data = {"nodes": [], "edges": []}
    if os.path.exists(json_path):
        with open(json_path, "r") as f:
            fd = json.load(f)
            circ = next((s for s in fd.get("signals", []) if s.get("signal_type") == "CIRCULAR_TRADING"), {})
            graph_data = circ.get("graph_data", {"nodes": [], "edges": []})
            
    nodes_json = json.dumps(graph_data.get("nodes", []))
    edges_json = json.dumps(graph_data.get("edges", []))
    
    html_content = f"""
    <html>
        <head>
            <title>Circular Trading Graph</title>
            <script type="text/javascript" src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
            <style type="text/css">
                #mynetwork {{
                    width: 100%;
                    height: 100vh;
                    border: none;
                    margin: 0;
                    padding: 0;
                    background-color: #F8FAFC;
                }}
                body {{ margin: 0; overflow: hidden; }}
            </style>
        </head>
        <body>
            <div id="mynetwork"></div>
            <script type="text/javascript">
                var rawNodes = {nodes_json};
                var rawEdges = {edges_json};
                
                // Standardize font mapping for VisJS
                var formattedNodes = rawNodes.map(function(n) {{
                    return {{
                        id: n.id,
                        label: n.label,
                        color: n.color,
                        font: {{ color: n.color === '#FF0000' || n.color === '#1C335B' ? 'white' : 'black', face: 'Inter' }},
                        shape: 'box',
                        margin: 10,
                        borderWidth: n.color === '#008000' ? 2 : 0,
                        borderColor: '#16A34A',
                        shadow: true
                    }};
                }});

                var formattedEdges = rawEdges.map(function(e) {{
                    return {{
                        from: e.from,
                        to: e.to,
                        label: e.label,
                        arrows: 'to',
                        font: {{ align: 'horizontal', face: 'Inter', color: '#64748B' }},
                        color: {{ color: '#94A3B8' }},
                        width: 2
                    }};
                }});
                
                var nodes = new vis.DataSet(formattedNodes);
                var edges = new vis.DataSet(formattedEdges);

                var container = document.getElementById('mynetwork');
                var data = {{ nodes: nodes, edges: edges }};
                var options = {{
                    edges: {{ smooth: {{ type: 'dynamic', roundness: 0.15 }} }},
                    physics: {{ 
                        stabilization: true,
                        barnesHut: {{
                            gravitationalConstant: -5000,
                            centralGravity: 0.1,
                            springLength: 250,
                            springConstant: 0.05,
                            avoidOverlap: 0.8
                        }}
                    }},
                    interaction: {{ dragNodes: true, dragView: true, zoomView: true }}
                }};
                
                if (formattedNodes.length > 0) {{
                     var network = new vis.Network(container, data, options);
                }} else {{
                     document.getElementById('mynetwork').innerHTML = "<div style='display:flex; height:100%; justify-content:center; alignItems:center; color:#16A34A; font-family:Inter; font-size: 1.25rem;'>No Circular Trade Graph Generated. Network is 100% Clean.</div>";
                }}
            </script>
        </body>
    </html>
    """
    return HTMLResponse(content=html_content, status_code=200)
